# Generated by Django 4.2.4 on 2023-09-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restourant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproductsmodel',
            options={'verbose_name': 'name', 'verbose_name_plural': 'names'},
        ),
    ]
